/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author aluno
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuItemHospede = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jMenuMovimentos = new javax.swing.JMenu();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jMenuPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        jMenuCadastros.setBackground(new java.awt.Color(204, 204, 204));
        jMenuCadastros.setForeground(new java.awt.Color(102, 102, 102));
        jMenuCadastros.setText("Cadastros");

        jMenuItemFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemFornecedor.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemFornecedor.setText("Fornecedor");
        jMenuCadastros.add(jMenuItemFornecedor);

        jMenuItemFuncionario.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemFuncionario.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItemFuncionario.setText("Funcionário");
        jMenuCadastros.add(jMenuItemFuncionario);

        jMenuItemHospede.setText("Hóspede");
        jMenuCadastros.add(jMenuItemHospede);
        jMenuCadastros.add(jSeparator1);

        jMenuItemProduto.setText("Produto");
        jMenuCadastros.add(jMenuItemProduto);

        jMenuPrincipal.add(jMenuCadastros);

        jMenuMovimentos.setBackground(new java.awt.Color(204, 204, 204));
        jMenuMovimentos.setForeground(new java.awt.Color(102, 102, 102));
        jMenuMovimentos.setText("Movimentos");
        jMenuPrincipal.add(jMenuMovimentos);

        jMenuRelatorios.setBackground(new java.awt.Color(204, 204, 204));
        jMenuRelatorios.setForeground(new java.awt.Color(102, 102, 102));
        jMenuRelatorios.setText("Relatórios");
        jMenuPrincipal.add(jMenuRelatorios);

        jMenuAjuda.setBackground(new java.awt.Color(204, 204, 204));
        jMenuAjuda.setForeground(new java.awt.Color(102, 102, 102));
        jMenuAjuda.setText("Ajuda");
        jMenuPrincipal.add(jMenuAjuda);

        jMenuSobre.setBackground(new java.awt.Color(204, 204, 204));
        jMenuSobre.setForeground(new java.awt.Color(102, 102, 102));
        jMenuSobre.setText("Sobre");
        jMenuPrincipal.add(jMenuSobre);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemHospede;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenu jMenuMovimentos;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
